version: "3.7"
services:
  frontend:
    build: .
    ports: 
      - 3000:3000
    environment:
      - API_HOST={$API_HOST}
  proxy:
    build: proxy
    ports:
      - ${PORT}:80
    depends_on: 
      - frontend
